// AUTO-GENERATED by tools/build_content.py — do not edit by hand.
// Pinyin from CC-CEDICT; glosses curated against the C101 English text.
window.C101.register(
{
  "id": "ch01",
  "title": "Chapter 1 — What Is Life?",
  "zh": "第一章：生命的意義",
  "lessons": [
    {
      "id": "ch01-l1",
      "title": "Nature of Man",
      "zh": "人的本質",
      "words": [
        {
          "hanzi": "生命",
          "pinyin": "shēng mìng",
          "en": "life (of a living being)"
        },
        {
          "hanzi": "意義",
          "pinyin": "yì yì",
          "en": "meaning; significance"
        },
        {
          "hanzi": "人生",
          "pinyin": "rén shēng",
          "en": "(human) life; one's life"
        },
        {
          "hanzi": "人性",
          "pinyin": "rén xìng",
          "en": "human nature"
        },
        {
          "hanzi": "本質",
          "pinyin": "běn zhì",
          "en": "essence; nature"
        },
        {
          "hanzi": "靈魂",
          "pinyin": "líng hún",
          "en": "soul"
        },
        {
          "hanzi": "肉體",
          "pinyin": "ròu tǐ",
          "en": "physical body; flesh"
        },
        {
          "hanzi": "問題",
          "pinyin": "wèn tí",
          "en": "question; problem"
        },
        {
          "hanzi": "答案",
          "pinyin": "dá àn",
          "en": "answer"
        },
        {
          "hanzi": "如果",
          "pinyin": "rú guǒ",
          "en": "if"
        },
        {
          "hanzi": "因為",
          "pinyin": "yīn wèi",
          "en": "because"
        },
        {
          "hanzi": "什麼",
          "pinyin": "shén me",
          "en": "what"
        }
      ]
    },
    {
      "id": "ch01-l2",
      "title": "The Creation Account",
      "zh": "創世記",
      "words": [
        {
          "hanzi": "創造",
          "pinyin": "chuàng zào",
          "en": "to create"
        },
        {
          "hanzi": "創造者",
          "pinyin": "chuàng zào zhě",
          "en": "creator"
        },
        {
          "hanzi": "宇宙",
          "pinyin": "yǔ zhòu",
          "en": "universe; cosmos"
        },
        {
          "hanzi": "起源",
          "pinyin": "qǐ yuán",
          "en": "origin"
        },
        {
          "hanzi": "聖經",
          "pinyin": "Shèng jīng",
          "en": "the Bible; scripture"
        },
        {
          "hanzi": "永恆",
          "pinyin": "yǒng héng",
          "en": "eternal; eternity"
        },
        {
          "hanzi": "渴望",
          "pinyin": "kě wàng",
          "en": "to long for; longing"
        },
        {
          "hanzi": "滿足",
          "pinyin": "mǎn zú",
          "en": "to satisfy; satisfied"
        },
        {
          "hanzi": "世界",
          "pinyin": "shì jiè",
          "en": "world"
        },
        {
          "hanzi": "存在",
          "pinyin": "cún zài",
          "en": "to exist; existence"
        },
        {
          "hanzi": "超越",
          "pinyin": "chāo yuè",
          "en": "to transcend; to surpass"
        },
        {
          "hanzi": "精神",
          "pinyin": "jīng shén",
          "en": "spirit; mind"
        }
      ]
    },
    {
      "id": "ch01-l3",
      "title": "In the Beginning",
      "zh": "太始之初",
      "words": [
        {
          "hanzi": "光",
          "pinyin": "guāng",
          "en": "light"
        },
        {
          "hanzi": "黑暗",
          "pinyin": "hēi àn",
          "en": "darkness"
        },
        {
          "hanzi": "早晨",
          "pinyin": "zǎo chén",
          "en": "morning"
        },
        {
          "hanzi": "晚上",
          "pinyin": "wǎn shang",
          "en": "evening; night"
        },
        {
          "hanzi": "動物",
          "pinyin": "dòng wù",
          "en": "animal"
        },
        {
          "hanzi": "生物",
          "pinyin": "shēng wù",
          "en": "living creature; organism"
        },
        {
          "hanzi": "形象",
          "pinyin": "xíng xiàng",
          "en": "image; likeness"
        },
        {
          "hanzi": "關係",
          "pinyin": "guān xì",
          "en": "relationship"
        },
        {
          "hanzi": "各種",
          "pinyin": "gè zhǒng",
          "en": "every kind of; various"
        },
        {
          "hanzi": "創世記",
          "pinyin": "Chuàng shì jì",
          "en": "Genesis (book of the Bible)"
        },
        {
          "hanzi": "實驗",
          "pinyin": "shí yàn",
          "en": "experiment"
        },
        {
          "hanzi": "重複",
          "pinyin": "chóng fù",
          "en": "to repeat; repeated"
        }
      ]
    },
    {
      "id": "ch01-l4",
      "title": "Anticipating Parent",
      "zh": "滿懷期待的父母",
      "words": [
        {
          "hanzi": "父母",
          "pinyin": "fù mǔ",
          "en": "parents"
        },
        {
          "hanzi": "期待",
          "pinyin": "qī dài",
          "en": "to look forward to; anticipation"
        },
        {
          "hanzi": "準備",
          "pinyin": "zhǔn bèi",
          "en": "to prepare"
        },
        {
          "hanzi": "寶寶",
          "pinyin": "bǎo bao",
          "en": "baby"
        },
        {
          "hanzi": "描述",
          "pinyin": "miáo shù",
          "en": "to describe"
        },
        {
          "hanzi": "依據",
          "pinyin": "yī jù",
          "en": "basis; according to"
        },
        {
          "hanzi": "按照",
          "pinyin": "àn zhào",
          "en": "according to; in accordance with"
        },
        {
          "hanzi": "心意",
          "pinyin": "xīn yì",
          "en": "intention; heart's desire"
        },
        {
          "hanzi": "非常",
          "pinyin": "fēi cháng",
          "en": "very; extremely"
        },
        {
          "hanzi": "甚至",
          "pinyin": "shèn zhì",
          "en": "even; to the point that"
        },
        {
          "hanzi": "認為",
          "pinyin": "rèn wéi",
          "en": "to think; to consider"
        },
        {
          "hanzi": "東西",
          "pinyin": "dōng xi",
          "en": "thing(s)"
        }
      ]
    },
    {
      "id": "ch01-l5",
      "title": "A Fork in the Road",
      "zh": "人生的十字路口",
      "words": [
        {
          "hanzi": "慈愛",
          "pinyin": "cí ài",
          "en": "loving; loving-kindness"
        },
        {
          "hanzi": "父親",
          "pinyin": "fù qīn",
          "en": "father"
        },
        {
          "hanzi": "智慧",
          "pinyin": "zhì huì",
          "en": "wisdom"
        },
        {
          "hanzi": "管理",
          "pinyin": "guǎn lǐ",
          "en": "to manage; to rule over"
        },
        {
          "hanzi": "大自然",
          "pinyin": "dà zì rán",
          "en": "nature (the natural world)"
        },
        {
          "hanzi": "萬物",
          "pinyin": "wàn wù",
          "en": "all things"
        },
        {
          "hanzi": "信仰",
          "pinyin": "xìn yǎng",
          "en": "faith; belief"
        },
        {
          "hanzi": "基督教",
          "pinyin": "Jī dū jiào",
          "en": "Christianity"
        },
        {
          "hanzi": "證據",
          "pinyin": "zhèng jù",
          "en": "evidence"
        },
        {
          "hanzi": "課程",
          "pinyin": "kè chéng",
          "en": "course; curriculum"
        },
        {
          "hanzi": "拒絕",
          "pinyin": "jù jué",
          "en": "to reject; to refuse"
        },
        {
          "hanzi": "價值",
          "pinyin": "jià zhí",
          "en": "value; worth"
        }
      ]
    }
  ],
  "sentences": [
    {
      "zh": "人生的意義是什麼？",
      "en": "What is the meaning of life?",
      "blank": "意義"
    },
    {
      "zh": "我是一個有靈魂的生命。",
      "en": "I am a living being with a soul.",
      "blank": "靈魂"
    },
    {
      "zh": "這些問題的答案很重要。",
      "en": "The answers to these questions matter.",
      "blank": "答案"
    },
    {
      "zh": "神創造了宇宙。",
      "en": "God created the universe.",
      "blank": "創造"
    },
    {
      "zh": "《聖經》告訴我們世界的起源。",
      "en": "The Bible tells us the origin of the world.",
      "blank": "起源"
    },
    {
      "zh": "人心渴望永恆。",
      "en": "The human heart longs for eternity.",
      "blank": "永恆"
    },
    {
      "zh": "神說要有光。",
      "en": "God said, “let there be light.”",
      "blank": "光"
    },
    {
      "zh": "神照著自己的形象造人。",
      "en": "God made man in his own image.",
      "blank": "形象"
    },
    {
      "zh": "《創世記》記載了各種動物。",
      "en": "Genesis records every kind of animal.",
      "blank": "動物"
    },
    {
      "zh": "父母期待寶寶的出生。",
      "en": "The parents look forward to the baby's birth.",
      "blank": "期待"
    },
    {
      "zh": "他們為寶寶準備了很多東西。",
      "en": "They prepared many things for the baby.",
      "blank": "準備"
    },
    {
      "zh": "慈愛的父親有智慧。",
      "en": "The loving father has wisdom.",
      "blank": "智慧"
    },
    {
      "zh": "神讓人管理大自然的萬物。",
      "en": "God lets man rule over all things in nature.",
      "blank": "管理"
    },
    {
      "zh": "這門課程講述基督教信仰。",
      "en": "This course teaches the Christian faith.",
      "blank": "信仰"
    }
  ]
}
);
