"""Generate src/lang-map.js — a Traditional→Simplified single-character map for
exactly the characters used in the content files, sourced from CC-CEDICT.

The app's canonical script is Traditional (the book's script). Simplified is a
display option (see src/lang.js); character-level conversion is enough for this
curated vocabulary. A few Traditional characters map to multiple Simplified
forms depending on sense (one-to-many); OVERRIDES pins the reading the book uses.

Run:  py tools/build_langmap.py    ->  src/lang-map.js
"""
import os, re, glob, json
from lib_cedict import CEDICT_PATH

HAN = re.compile(r"[㐀-鿿]")

# One-to-many Traditional chars: pin the Simplified form the C101 text uses.
OVERRIDES = {
    "著": "着",   # 照著 -> 照着 (verb aspect marker), not 著 (zhu4)
}

def char_map():
    """Traditional single char -> Simplified single char, from CC-CEDICT's
    single-character entries (first entry wins)."""
    m = {}
    with open(CEDICT_PATH, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            mm = re.match(r"^(\S+)\s+(\S+)\s+\[", line)
            if not mm:
                continue
            trad, simp = mm.group(1), mm.group(2)
            if len(trad) == 1 and len(simp) == 1 and simp != trad:
                m.setdefault(trad, simp)
    return m

def content_chars():
    """Every Han character that appears in any content/*.js file, plus the few
    chrome strings the UI renders from JS (the 課程 101 brand)."""
    chars = set("課程")
    root = os.path.join(os.path.dirname(__file__), "..")
    for path in glob.glob(os.path.join(root, "content", "*.js")):
        with open(path, encoding="utf-8") as f:
            for ch in f.read():
                if HAN.match(ch):
                    chars.add(ch)
    return chars

def main():
    cmap = char_map()
    cmap.update(OVERRIDES)
    used = content_chars()
    out = {c: cmap[c] for c in sorted(used) if c in cmap and cmap[c] != c}

    js = ("// AUTO-GENERATED by tools/build_langmap.py — do not edit by hand.\n"
          "// Traditional->Simplified for the characters used in content/*.js\n"
          "// (source: CC-CEDICT). Consumed by src/lang.js for the script toggle.\n"
          "window.C101_LANGMAP = "
          + json.dumps(out, ensure_ascii=False, indent=0).replace("\n", "")
          + ";\n")

    dest = os.path.join(os.path.dirname(__file__), "..", "src", "lang-map.js")
    open(dest, "w", encoding="utf-8").write(js)
    print("wrote", dest, "-", len(out), "characters mapped")

if __name__ == "__main__":
    main()
